

spring:
  datasource:
    url: jdbc:postgresql://postgres:vlNo4SmfiOsFoMDSZZlY@containers-us-west-93.railway.app:6171/railway
    username: postgres
    password: vlNo4SmfiOsFoMDSZZlY
    name: consultaprecos

  sql:
    init:
      mode: always # you won't do this in prod, I'm just doing this for demo purposes
